import pandas as pd
data = pd.read_table('C:\\Users\\123\\Desktop\\files\\beijing_wangjing_125.txt', sep = ',')
data['daily_10min'] = data['daily_10min'].astype(str)
data['daily_10min'] = pd.to_datetime(data['daily_10min'])
df_group = data.groupby(['id'])
key_list = list(df_group.groups.keys())
temp = df_group.get_group(137)
temp = temp.sort_values(by='daily_10min')
# temp.set_index('daily_10min', inplace=True, drop=False)
# temp = temp.resample('10Min').ffill()
# temp = temp.between_time(start_time='00:00:00', end_time='23:50:00')
# nan = temp['real_speed'].isnull().sum(axis=0)
# per = temp['real_speed'].isnull().mean()
# temp = temp.drop(labels='id',axis=1)
# temp = temp.drop(labels='free_speed',axis=1)
# temp = temp.drop(labels='idx',axis=1)
temp.to_csv('C:\\Users\\123\\Desktop\\files\\{}.csv'.format(137), sep=',', index=False)
#print(nan,per)